name: Deploy API

on:
  push:
    paths:
      - 'faktorio-api/**'
      - '.github/workflows/deploy-api.yaml'

    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    name: Deploy API
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install deps (with cache)
        run: pnpm install

      - name: Deploy API
        uses: cloudflare/wrangler-action@v3
        env:
          TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MAILJET_API_KEY: ${{ secrets.MAILJET_API_KEY }}
          MAILJET_API_SECRET: ${{ secrets.MAILJET_API_SECRET }}
        with:
          packageManager: pnpm
          secrets: |
            TURSO_DATABASE_URL
            TURSO_AUTH_TOKEN
            CLERK_SECRET_KEY
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: './faktorio-api'
