name: Deploy FE

on:
  push:
    paths:
      - 'faktorio-fe/**'
      - '.github/workflows/deploy-fe.yaml'

    branches:
      - main

jobs:
  deploy-fe:
    runs-on: ubuntu-latest
    name: Deploy Frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps (with cache)
        run: pnpm install
        cache: 'pnpm'

      - name: Build
        working-directory: ./faktorio-fe
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_CLERK_PUBLISHABLE_KEY: ${{ vars.VITE_CLERK_PUBLISHABLE_KEY }}
        run: pnpm build

      - name: Deploy Frontend
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: pnpm
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: './faktorio-fe'
          command: pages deploy dist --projectName faktorio
